apiVersion: v1
kind: Service
metadata:
  name: gnavi4-frontend
  namespace: sk-team-04
spec:
  selector:
    app: gnavi4-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP